version: '3.8'

services:
  app:
    image: node:latest
    restart: always
    ports:
      - "3002:3002"
      - "161:161"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    networks:
      - shared-network
    environment:
      - HOSTGRPCASESORIAS=app:164
      - GRPCPORTUSUARIOS=app:161
    depends_on:
      - db2
    command: sh -c "rm -rf node_modules && npm install && node app.js"

  db2:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DBPASSWORD}
    ports:
      - "3310:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./usuarios_testing.sql:/docker-entrypoint-initdb.d/usuarios_testing.sql
    networks:
      - shared-network


volumes:
  db_data:

networks:
  shared-network:
    driver: bridge
    external: true

